from main import transform_columns_to_float
import polars as pl


def test_transform_columns_to_float():
    input_df = pl.DataFrame(
        [
            {
                "UID": "719601",
                "Mins": "4,064",
                "Hdrs A": "453",
                "Clear": "69.00",
                "Cr A": "24",
                "Drb": "25",
                "FA": "92",
                "Itc": "16",
                "Pas A": "1,594",
                "Ps C": "1,362",
                "Shots": "261",
                "Pens": "15",
                "Tck W": "33",
                "Tck R": "69%",
                "Yel": "4",
                "Red": "0",
                "Fls": "35",
                "CCC": "35",
            },
            {
                "UID": "29179241",
                "Mins": "4,025",
                "Hdrs A": "610",
                "Clear": "85.00",
                "Cr A": "67",
                "Drb": "70",
                "FA": "133",
                "Itc": "30",
                "Pas A": "1,704",
                "Ps C": "1,429",
                "Shots": "289",
                "Pens": "9",
                "Tck W": "37",
                "Tck R": "79%",
                "Yel": "1",
                "Red": "0",
                "Fls": "42",
                "CCC": "42",
            },
            {
                "UID": "62182055",
                "Mins": "3,950",
                "Hdrs A": "472",
                "Clear": "51.00",
                "Cr A": "30",
                "Drb": "38",
                "FA": "110",
                "Itc": "34",
                "Pas A": "1,682",
                "Ps C": "1,395",
                "Shots": "195",
                "Pens": "10",
                "Tck W": "19",
                "Tck R": "61%",
                "Yel": "1",
                "Red": "0",
                "Fls": "54",
                "CCC": "54",
            },
        ]
    )
    # output data
    output_df = transform_columns_to_float(input_df)
    # expected output
    expected_df = pl.DataFrame(
        [
            {
                "UID": "719601",
                "Mins": 4064.0,
                "Hdrs A": 453.0,
                "Clear": 69.0,
                "Cr A": 24.0,
                "Drb": 25.0,
                "FA": 92.0,
                "Itc": 16.0,
                "Pas A": 1594.0,
                "Ps C": 1362.0,
                "Shots": 261.0,
                "Pens": 15.0,
                "Tck W": 33.0,
                "Tck R": 0.6900000000000001,
                "Yel": 4.0,
                "Red": 0.0,
                "Fls": 35.0,
                "CCC": 35.0,
            },
            {
                "UID": "29179241",
                "Mins": 4025.0,
                "Hdrs A": 610.0,
                "Clear": 85.0,
                "Cr A": 67.0,
                "Drb": 70.0,
                "FA": 133.0,
                "Itc": 30.0,
                "Pas A": 1704.0,
                "Ps C": 1429.0,
                "Shots": 289.0,
                "Pens": 9.0,
                "Tck W": 37.0,
                "Tck R": 0.79,
                "Yel": 1.0,
                "Red": 0.0,
                "Fls": 42.0,
                "CCC": 42.0,
            },
            {
                "UID": "62182055",
                "Mins": 3950.0,
                "Hdrs A": 472.0,
                "Clear": 51.0,
                "Cr A": 30.0,
                "Drb": 38.0,
                "FA": 110.0,
                "Itc": 34.0,
                "Pas A": 1682.0,
                "Ps C": 1395.0,
                "Shots": 195.0,
                "Pens": 10.0,
                "Tck W": 19.0,
                "Tck R": 0.61,
                "Yel": 1.0,
                "Red": 0.0,
                "Fls": 54.0,
                "CCC": 54.0,
            },
        ]
    )
    assert output_df.equals(expected_df)
