from get_players_data import get_players_data
import filecmp
from pathlib import Path
import polars as pl


def test_get_players_data():
    file_path = r"C:\Users\d_roe\Documents\VS Code Projects\Portfolio\DE-2026-004\tests\fixtures\players.html"

    output = get_players_data(file_path)

    df = get_players_data(file_path)

    expected_schema = [
        "UID",
        "Inf",
        "Name",
        "Club",
        "Best Pos",
        "Right Foot",
        "Left Foot",
        "Mins",
        "Hdrs",
        "Hdrs A",
        "Clear",
        "Cr A",
        "Cr C",
        "Distance",
        "Drb",
        "FA",
        "Off",
        "Itc",
        "Pas A",
        "Ps C",
        "CCC",
        "Shots",
        "xG",
        "Pens",
        "Tck W",
        "Tck R",
        "Yel",
        "Red",
        "Fls",
        "Min WD",
        "Max WD",
        "Min AP",
        "Max AP",
        "Rec",
    ]

    expected_rows = [
        [
            "719601",
            "",
            "Robert Lewandowski - Polish",
            "FC Bayern",
            "ST (C)",
            "Very Strong",
            "Fairly Strong",
            "4,064",
            "278",
            "453",
            "69.00",
            "24",
            "5",
            "535.1km",
            "25",
            "92",
            "25",
            "16",
            "1,594",
            "1,362",
            "13",
            "261",
            "40.84",
            "15",
            "33",
            "69%",
            "4",
            "0",
            "35",
            "N/A",
            "N/A",
            "-",
            "-",
            "- -  -  - ",
        ],
        [
            "29179241",
            "Inj",
            "Erling Haaland - Norwegian",
            "Borussia Dortmund",
            "ST (C)",
            "Reasonable",
            "Very Strong",
            "4,025",
            "353",
            "610",
            "85.00",
            "67",
            "11",
            "591.8km",
            "70",
            "133",
            "33",
            "30",
            "1,704",
            "1,429",
            "24",
            "289",
            "37.00",
            "9",
            "37",
            "79%",
            "1",
            "0",
            "42",
            "£11,399,000 p/a",
            "£15,733,000 p/a",
            "£114M",
            "£134M",
            "- -  -  - ",
        ],
        [
            "62182055",
            "nEU",
            "Dušan Vlahović - Serbian",
            "Zebre",
            "ST (C)",
            "Reasonable",
            "Very Strong",
            "3,950",
            "292",
            "472",
            "51.00",
            "30",
            "7",
            "542.0km",
            "38",
            "110",
            "36",
            "34",
            "1,682",
            "1,395",
            "8",
            "195",
            "26.04",
            "10",
            "19",
            "61%",
            "1",
            "0",
            "54",
            "£11,748,000 p/a",
            "£15,313,000 p/a",
            "£74M",
            "£92M",
            "- -  -  - ",
        ],
    ]

    expected = pl.DataFrame(expected_rows, schema=expected_schema, orient="row")

    assert df.head(3).equals(
        expected
    ), "The first three rows of the DataFrame do not match the expected output."
