from transform_columns_to_float import transform_columns_to_float
import polars as pl


def test_transform_columns_to_float():
    input_df = pl.DataFrame(
        [
            {
                "UID": "719601",
                "Mins": "4,064",
                "Hdrs A": "453",
                "Clear": "69.00",
                "Cr A": "24",
                "Drb": "25",
                "FA": "92",
                "Itc": "16",
                "Pas A": "1,594",
                "Ps C": "1,362",
                "Shots": "261",
                "Pens": "15",
                "Tck W": "33",
                "Tck R": "69%",
                "Yel": "4",
                "Red": "0",
                "Fls": "35",
            },
            {
                "UID": "29179241",
                "Mins": "4,025",
                "Hdrs A": "610",
                "Clear": "85.00",
                "Cr A": "67",
                "Drb": "70",
                "FA": "133",
                "Itc": "30",
                "Pas A": "1,704",
                "Ps C": "1,429",
                "Shots": "289",
                "Pens": "9",
                "Tck W": "37",
                "Tck R": "79%",
                "Yel": "1",
                "Red": "0",
                "Fls": "42",
            },
            {
                "UID": "62182055",
                "Mins": "3,950",
                "Hdrs A": "472",
                "Clear": "51.00",
                "Cr A": "30",
                "Drb": "38",
                "FA": "110",
                "Itc": "34",
                "Pas A": "1,682",
                "Ps C": "1,395",
                "Shots": "195",
                "Pens": "10",
                "Tck W": "19",
                "Tck R": "61%",
                "Yel": "1",
                "Red": "0",
                "Fls": "54",
            },
        ]
    )
    # output data
    output_df = transform_columns_to_float(input_df)
    # expected output
    expected_df = pl.DataFrame(
        [
            {
                "UID": "719601",
                "Mins": "4,064",
                "Hdrs A": "453",
                "Clear": "69.00",
                "Cr A": "24",
                "Drb": "25",
                "FA": "92",
                "Itc": "16",
                "Pas A": "1,594",
                "Ps C": "1,362",
                "Shots": "261",
                "Pens": "15",
                "Tck W": "33",
                "Tck R": "69%",
                "Yel": "4",
                "Red": "0",
                "Fls": "35",
                "Mins - float": 4064.0,
                "Hdrs A - float": 453.0,
                "Clear - float": 69.0,
                "Cr A - float": 24.0,
                "Drb - float": 25.0,
                "FA - float": 92.0,
                "Itc - float": 16.0,
                "Pas A - float": 1594.0,
                "Ps C - float": 1362.0,
                "Shots - float": 261.0,
                "Pens - float": 15.0,
                "Tck W - float": 33.0,
                "Tck R - float": 0.6900000000000001,
                "Yel - float": 4.0,
                "Red - float": 0.0,
                "Fls - float": 35.0,
            },
            {
                "UID": "29179241",
                "Mins": "4,025",
                "Hdrs A": "610",
                "Clear": "85.00",
                "Cr A": "67",
                "Drb": "70",
                "FA": "133",
                "Itc": "30",
                "Pas A": "1,704",
                "Ps C": "1,429",
                "Shots": "289",
                "Pens": "9",
                "Tck W": "37",
                "Tck R": "79%",
                "Yel": "1",
                "Red": "0",
                "Fls": "42",
                "Mins - float": 4025.0,
                "Hdrs A - float": 610.0,
                "Clear - float": 85.0,
                "Cr A - float": 67.0,
                "Drb - float": 70.0,
                "FA - float": 133.0,
                "Itc - float": 30.0,
                "Pas A - float": 1704.0,
                "Ps C - float": 1429.0,
                "Shots - float": 289.0,
                "Pens - float": 9.0,
                "Tck W - float": 37.0,
                "Tck R - float": 0.79,
                "Yel - float": 1.0,
                "Red - float": 0.0,
                "Fls - float": 42.0,
            },
            {
                "UID": "62182055",
                "Mins": "3,950",
                "Hdrs A": "472",
                "Clear": "51.00",
                "Cr A": "30",
                "Drb": "38",
                "FA": "110",
                "Itc": "34",
                "Pas A": "1,682",
                "Ps C": "1,395",
                "Shots": "195",
                "Pens": "10",
                "Tck W": "19",
                "Tck R": "61%",
                "Yel": "1",
                "Red": "0",
                "Fls": "54",
                "Mins - float": 3950.0,
                "Hdrs A - float": 472.0,
                "Clear - float": 51.0,
                "Cr A - float": 30.0,
                "Drb - float": 38.0,
                "FA - float": 110.0,
                "Itc - float": 34.0,
                "Pas A - float": 1682.0,
                "Ps C - float": 1395.0,
                "Shots - float": 195.0,
                "Pens - float": 10.0,
                "Tck W - float": 19.0,
                "Tck R - float": 0.61,
                "Yel - float": 1.0,
                "Red - float": 0.0,
                "Fls - float": 54.0,
            },
        ]
    )
    assert output_df.equals(expected_df)
